#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Theano
Version  : 0.9.0
Release  : 11
URL      : http://pypi.debian.net/Theano/Theano-0.9.0.tar.gz
Source0  : http://pypi.debian.net/Theano/Theano-0.9.0.tar.gz
Summary  : Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: Theano-bin
Requires: Theano-python
Requires: Sphinx
Requires: flake8
Requires: nose
Requires: nose-parameterized
Requires: numpy
Requires: scipy
Requires: six
BuildRequires : Sphinx
BuildRequires : beignet
BuildRequires : beignet-dev
BuildRequires : graphviz
BuildRequires : nose
BuildRequires : numpy
BuildRequires : ocl-icd
BuildRequires : ocl-icd-dev
BuildRequires : openblas
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : scipy
BuildRequires : setuptools
BuildRequires : six

%description
To install the package, see this page:
http://deeplearning.net/software/theano/install.html

%package bin
Summary: bin components for the Theano package.
Group: Binaries

%description bin
bin components for the Theano package.


%package python
Summary: python components for the Theano package.
Group: Default
Provides: theano-python

%description python
python components for the Theano package.


%prep
%setup -q -n Theano-0.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505443336
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/theano-cache
/usr/bin/theano-nose

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
